Universe        = vanilla
Notification    = Complete
Executable      = /phenix/u/zji/bin/condor-root.csh
Arguments       = $(Initialdir) anaPileup_Isolated.C $(Process)
Requirements    = (CPU_Speed >= 1)
Rank		= CPU_Speed
request_memory  = 128M
request_cpus    = 1
Priority        = 20
GetEnv          = False
Initialdir      = $ENV(PWD)
Input           = /dev/null
Output          = /dev/null
Error           = /dev/null
Log             = /dev/null
Notify_user     = zji@rcf.rhic.bnl.gov
Queue 9
