Universe        = vanilla
Notification    = Complete
Executable      = /phenix/u/zji/bin/condor-bash.csh
Arguments       = $(Initialdir) pythiaToDST.sh $(Process)
Requirements    = (CPU_Speed >= 2)
Rank		= CPU_Speed
request_memory  = 1.4G
request_cpus    = 1
Priority        = 20
GetEnv          = False
Initialdir      = $ENV(PWD)
Input           = /dev/null
Output          = /dev/null
Error           = /dev/null
Log             = /dev/null
Notify_user     = zji@rcf.rhic.bnl.gov
Queue 4500
